name: DeanFlory
favicon: null
layout_spectrum: 0.20536711299791932
typography_spectrum: 0.4475167093332857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4032096688169986
  lightness: 0.7662612767890096
  saturation: 0.809815539047122
  rhythmicContrast: 0.9531458567362279
purpose: []
